import test from "node:test";
import assert from "node:assert/strict";
import { readSource, sourceExists } from "../../../../helpers/source-readers.mjs";

test("/internal/demo-sections exists as a noindex UI demo route for preserved orphan section components", () => {
  const file = "src/app/internal/demo-sections/page.tsx";
  assert.equal(sourceExists(file), true, `${file} should exist`);

  const source = readSource(file);
  assert.match(source, /title:\s*"Internal Demo Sections \| QueryPie AI"/);
  assert.match(source, /canonical:\s*"\/internal\/demo-sections"/);
  assert.match(source, /robots:\s*\{\s*index: false,\s*follow: false,\s*\}/s);
  assert.match(source, /@\/components\/sections\/internal-demo\/role-slides/);
  assert.match(source, /@\/components\/sections\/internal-demo\/use-case-showcase/);
  assert.match(source, /@\/components\/sections\/internal-demo\/ai-crew-avatar/);
  assert.match(source, /@\/components\/sections\/internal-demo\/ai-dashi-faq/);
  assert.doesNotMatch(source, /\.\/role-slides/);
  assert.doesNotMatch(source, /\.\/use-case-showcase/);
  assert.doesNotMatch(source, /\.\/ai-crew-avatar/);
  assert.doesNotMatch(source, /\.\/ai-dashi-faq/);
  assert.doesNotMatch(source, /@\/components\/sections\/ai-crew\/avatar/);
  assert.doesNotMatch(source, /@\/components\/sections\/ai-dashi\/faq/);
  assert.equal(sourceExists("src/app/internal/demo-sections/role-slides.tsx"), false);
  assert.equal(sourceExists("src/app/internal/demo-sections/use-case-showcase.tsx"), false);
  assert.equal(sourceExists("src/app/internal/demo-sections/ai-crew-avatar.tsx"), false);
  assert.equal(sourceExists("src/app/internal/demo-sections/ai-dashi-faq.tsx"), false);
  assert.equal(sourceExists("src/components/sections/ai-crew/avatar.tsx"), false);
  assert.equal(sourceExists("src/components/sections/ai-dashi/faq.tsx"), false);
  assert.equal(sourceExists("src/components/sections/internal-demo/role-slides.tsx"), true);
  assert.equal(sourceExists("src/components/sections/internal-demo/use-case-showcase.tsx"), true);
  assert.equal(sourceExists("src/components/sections/internal-demo/ai-crew-avatar.tsx"), true);
  assert.equal(sourceExists("src/components/sections/internal-demo/ai-dashi-faq.tsx"), true);
  assert.equal(sourceExists("src/components/sections/role-slides.tsx"), false);
  assert.equal(sourceExists("src/components/sections/use-case-showcase.tsx"), false);
  assert.match(source, /RoleSlides/);
  assert.match(source, /RoleSlide/);
  assert.match(source, /RolePainPoint/);
  assert.match(source, /RoleCatchCopy/);
  assert.match(source, /RoleSummary/);
  assert.match(source, /UseCaseShowcase/);
  assert.match(source, /UseCaseCard/);
  assert.match(source, /UseCaseBody/);
  assert.match(source, /UseCaseTab/);
  assert.match(source, /AICrewAvatar/);
  assert.match(source, /AIDashiFaq/);
  assert.match(source, /AIDashiFaqQuestion/);
  assert.match(source, /ctaHref={aiDashiConsultUrl}/);
  assert.doesNotMatch(source, /roleSlidesDemoProps/);
  assert.doesNotMatch(source, /useCaseShowcaseDemoProps/);
  assert.doesNotMatch(source, /aiDashiFaqItems/);
  assert.doesNotMatch(source, /<section className=/);
  assert.doesNotMatch(source, /<article className=/);
  assert.match(source, /InternalDemoSection/);
  assert.match(source, /InternalDemoIntro/);
  assert.match(source, /InternalDemoCardGrid/);
  assert.match(source, /section component を削除せず/);
  assert.match(source, /internal 専用デモルートから明示的に接続/);
  assert.match(source, /RoleSlides component demo/);
  assert.match(source, /UseCaseShowcase component demo/);
  assert.match(source, /AICrewAvatar component demo/);
  assert.match(source, /AIDashiFaq component demo/);
  assert.match(source, /Issue 395 survivors/);
  assert.match(source, /internal demo 専用 visual primitive/);
  assert.match(source, /FAQ の文言と CTA は page\.tsx が直接所有/);
  assert.match(source, /canonical route へ戻す判断/);
  assert.match(source, /\/demo\/use-cases/);
  assert.match(source, /\/contact-us\?inquiry=ai-consulting&product=ai-crew/);
});
