import test from "node:test";
import assert from "node:assert/strict";
import { readSource } from "../../../../helpers/source-readers.mjs";

test("/t/plans keeps copy and comparison composition in the route while the section module only provides pricing UI primitives", () => {
  const routeSource = readSource("src/app/t/plans/page.tsx");
  const sectionSource = readSource("src/components/sections/plans/section.tsx");

  assert.match(routeSource, /from "@\/components\/sections\/plans\/section"/);
  assert.match(routeSource, /<PricingRoot>/);
  assert.match(routeSource, /<PricingHeader>/);
  assert.match(routeSource, /<PricingContextProvider defaultActiveTab="aip">/);
  assert.match(routeSource, /<ProductTabs>/);
  assert.match(routeSource, /<ProductTab name="aip">/);
  assert.match(routeSource, /<ProductTab name="acp">/);
  assert.match(routeSource, /<PlanVisibility id="aip">/);
  assert.match(routeSource, /<PlanVisibility id="acp">/);
  assert.match(routeSource, /<PlanCard type="primary">/);
  assert.match(routeSource, /<PlanCard type="black">/);
  assert.match(routeSource, /<PlanFeature supported=\{true\}>月間800クレジット<\/PlanFeature>/);
  assert.match(routeSource, /<CompareTable>/);
  assert.match(routeSource, /<CompareTableHead>/);
  assert.match(routeSource, /<CompareTableSection title="一般">/);
  assert.match(routeSource, /<CompareTableRow label="料金">/);
  assert.match(routeSource, /<CompareTableTextCell isBold>\$20\/月<\/CompareTableTextCell>/);
  assert.match(routeSource, /<CompareTableBooleanCell supported=\{false\} \/>/);
  assert.match(routeSource, /<CompareTableCheckLabelCell>最大30日間<\/CompareTableCheckLabelCell>/);
  assert.match(routeSource, /href="\/contact-us\?inquiry=quote-request&product=acp"/);

  assert.doesNotMatch(routeSource, /PlansPreviewPage/);
  assert.doesNotMatch(routeSource, /const Pricing = Object\.assign/);
  assert.doesNotMatch(routeSource, /const Plan = Object\.assign/);
  assert.doesNotMatch(routeSource, /rows=\{\[/);
  assert.doesNotMatch(routeSource, /columns=\{\[/);
  assert.doesNotMatch(routeSource, /const aipPlans\s*:/);
  assert.doesNotMatch(routeSource, /const acpPlans\s*:/);
  assert.doesNotMatch(routeSource, /const aipComparisonGroups\s*:/);
  assert.doesNotMatch(routeSource, /products=\{\[/);
  assert.doesNotMatch(routeSource, /PlansProductSwitcher/);

  assert.match(sectionSource, /export function PricingRoot\(/);
  assert.match(sectionSource, /export function PricingHeader\(/);
  assert.match(sectionSource, /export function PricingContextProvider/);
  assert.match(sectionSource, /searchParams\.has\("acp"\)/);
  assert.match(sectionSource, /export function PlanRoot\(/);
  assert.match(sectionSource, /export function PlanCard\(/);
  assert.match(sectionSource, /function ButtonChevronIcon\(/);
  assert.match(sectionSource, /viewBox="0 0 7 12"/);
  assert.match(sectionSource, /M7 6L0\.865033 12L0 11\.154L5\.26381 6L0 0\.846L0\.865033 0L7 6Z/);
  assert.match(sectionSource, /export function PlanVisibility/);
  assert.match(sectionSource, /export function CompareTable\(/);
  assert.match(sectionSource, /export function CompareTableHead\(/);
  assert.match(sectionSource, /export function CompareTableSection\(/);
  assert.match(sectionSource, /export function CompareTableRow\(/);
  assert.match(sectionSource, /export function CompareTableTextCell\(/);
  assert.match(sectionSource, /export function CompareTableBooleanCell\(/);
  assert.match(sectionSource, /export function CompareTableCheckLabelCell\(/);
  assert.match(sectionSource, /cloneElement\(child as ReactElement<ProductTabProps>, \{/);
  assert.match(sectionSource, /border-b-2 border-\[#dae1e7\]/);
  assert.match(sectionSource, /flex-1 cursor-pointer/);
  assert.match(sectionSource, /gap-20/);
  assert.match(sectionSource, /bg-\[linear-gradient\(180deg,#edf0f7_0%,#edf0f7_26\.89%,rgba\(255,255,255,0\)_60%\)\]/);
  assert.match(sectionSource, /radial-gradient\(126\.36%_70\.17%_at_50%_86\.97%,#fff_0%,rgba\(255,255,255,0\)_100%\)/);
  assert.match(sectionSource, /rounded-t-\[20px\]/);
  assert.match(sectionSource, /w-\[230px\]/);
  assert.match(sectionSource, /w-\[1200px\]/);
  assert.match(sectionSource, /-mx-6 w-\[calc\(100%\+48px\)\] overflow-x-auto px-6/);
  assert.match(sectionSource, /sm:-mx-10 sm:w-\[calc\(100%\+80px\)\] sm:px-10/);
  assert.match(sectionSource, /h-8 bg-\[#24292f\] text-white/);
  assert.match(sectionSource, /pl-5 text-left text-xs font-medium leading-\[17px\] tracking-\[0\.24px\]/);
  assert.match(sectionSource, /h-11 border-b border-\[#dae1e7\]/);

  assert.doesNotMatch(sectionSource, /rounded-\[28px\] border border-slate-200/);
  assert.doesNotMatch(sectionSource, /shadow-\[0_14px_40px/);
  assert.doesNotMatch(sectionSource, />\s*↗\s*</);
  assert.doesNotMatch(sectionSource, /bg-slate-50 text-slate-950/);
  assert.doesNotMatch(sectionSource, /lg:grid-cols-3/);

  assert.doesNotMatch(sectionSource, /export const Pricing = Object\.assign/);
  assert.doesNotMatch(sectionSource, /export const Plan = Object\.assign/);
  assert.doesNotMatch(sectionSource, /type CompareTableColumn =/);
  assert.doesNotMatch(sectionSource, /type CompareTableRowGroup =/);
});
