import test from "node:test";
import assert from "node:assert/strict";
import { readSource } from "../../../../helpers/source-readers.mjs";

test("/t/plans keeps copy and comparison composition in the route while the section module only provides pricing UI primitives", () => {
  const routeSource = readSource("src/app/t/plans/page.tsx");
  const aipRouteSource = readSource("src/app/t/plans/aip/page.tsx");
  const acpRouteSource = readSource("src/app/t/plans/acp/page.tsx");
  const contentSource = readSource("src/app/t/plans/plans-page-content.tsx");
  const sectionSource = readSource("src/components/sections/plans/section.tsx");

  assert.match(routeSource, /return <PlansPageContent activeProduct="aip" \/>/);
  assert.match(routeSource, /redirect\(redirectTarget\)/);
  assert.match(routeSource, /return `plans\/\$\{product\}/);
  assert.match(aipRouteSource, /canonical: "\/t\/plans\/aip"/);
  assert.match(aipRouteSource, /return <PlansPageContent activeProduct="aip" \/>/);
  assert.match(acpRouteSource, /canonical: "\/t\/plans\/acp"/);
  assert.match(acpRouteSource, /return <PlansPageContent activeProduct="acp" \/>/);
  assert.doesNotMatch(aipRouteSource, /<PricingRoot>|<PlanCard|<CompareTable>/);
  assert.doesNotMatch(acpRouteSource, /<PricingRoot>|<PlanCard|<CompareTable>/);

  assert.match(contentSource, /from "@\/components\/sections\/plans\/section"/);
  assert.match(contentSource, /<PricingRoot>/);
  assert.match(contentSource, /<PricingHeader>/);
  assert.match(contentSource, /<PricingContextProvider defaultActiveTab=\{activeProduct\}>/);
  assert.match(contentSource, /<ProductTabs>/);
  assert.match(contentSource, /<ProductTab name="aip">/);
  assert.match(contentSource, /<ProductTab name="acp">/);
  assert.match(contentSource, /<PlanVisibility id="aip">/);
  assert.match(contentSource, /<PlanVisibility id="acp">/);
  assert.match(contentSource, /<PlanCard type="primary">/);
  assert.match(contentSource, /<PlanCard type="black">/);
  assert.match(contentSource, /<PlanFeature supported=\{true\}>月間800クレジット<\/PlanFeature>/);
  assert.match(contentSource, /<CompareTable>/);
  assert.match(contentSource, /<CompareTableHead>/);
  assert.match(contentSource, /<CompareTableSection title="一般">/);
  assert.match(contentSource, /<CompareTableRow label="料金">/);
  assert.match(contentSource, /<CompareTableTextCell isBold>\$20\/月<\/CompareTableTextCell>/);
  assert.match(contentSource, /<CompareTableBooleanCell supported=\{false\} \/>/);
  assert.match(contentSource, /<CompareTableCheckLabelCell>最大30日間<\/CompareTableCheckLabelCell>/);
  assert.match(contentSource, /href="\/contact-us\?inquiry=quote-request&product=acp"/);

  assert.doesNotMatch(contentSource, /href="\/t\/plans\//);
  assert.doesNotMatch(contentSource, /PlansPreviewPage/);
  assert.doesNotMatch(contentSource, /const Pricing = Object\.assign/);
  assert.doesNotMatch(contentSource, /const Plan = Object\.assign/);
  assert.doesNotMatch(contentSource, /rows=\{\[/);
  assert.doesNotMatch(contentSource, /columns=\{\[/);
  assert.doesNotMatch(contentSource, /const aipPlans\s*:/);
  assert.doesNotMatch(contentSource, /const acpPlans\s*:/);
  assert.doesNotMatch(contentSource, /const aipComparisonGroups\s*:/);
  assert.doesNotMatch(contentSource, /products=\{\[/);
  assert.doesNotMatch(contentSource, /PlansProductSwitcher/);

  assert.match(sectionSource, /export function PricingRoot\(/);
  assert.match(sectionSource, /export function PricingHeader\(/);
  assert.match(sectionSource, /export function PricingContextProvider/);
  assert.match(sectionSource, /searchParams\.has\("acp"\)/);
  assert.match(sectionSource, /usePathname\(\)/);
  assert.match(sectionSource, /function getPlansProductHref\(pathname: string, product: string\)/);
  assert.match(sectionSource, /lastSegment === "aip" \|\| lastSegment === "acp"/);
  assert.match(sectionSource, /href: getPlansProductHref\(pathname, name\)/);
  assert.doesNotMatch(sectionSource, /href=\{`\/t\/plans/);
  assert.match(sectionSource, /export function PlanRoot\(/);
  assert.match(sectionSource, /export function PlanCard\(/);
  assert.match(sectionSource, /function ButtonChevronIcon\(/);
  assert.match(sectionSource, /viewBox="0 0 7 12"/);
  assert.match(sectionSource, /M7 6L0\.865033 12L0 11\.154L5\.26381 6L0 0\.846L0\.865033 0L7 6Z/);
  assert.match(sectionSource, /export function PlanVisibility/);
  assert.match(sectionSource, /export function CompareTable\(/);
  assert.match(sectionSource, /export function CompareTableHead\(/);
  assert.match(sectionSource, /export function CompareTableSection\(/);
  assert.match(sectionSource, /export function CompareTableRow\(/);
  assert.match(sectionSource, /export function CompareTableTextCell\(/);
  assert.match(sectionSource, /export function CompareTableBooleanCell\(/);
  assert.match(sectionSource, /export function CompareTableCheckLabelCell\(/);
  assert.match(sectionSource, /cloneElement\(child as ReactElement<ProductTabProps>, \{/);
  assert.match(sectionSource, /border-b-2 border-\[#dae1e7\]/);
  assert.match(sectionSource, /flex-1 cursor-pointer/);
  assert.match(sectionSource, /gap-20/);
  assert.match(sectionSource, /bg-\[linear-gradient\(180deg,#edf0f7_0%,#edf0f7_26\.89%,rgba\(255,255,255,0\)_60%\)\]/);
  assert.match(sectionSource, /radial-gradient\(126\.36%_70\.17%_at_50%_86\.97%,#fff_0%,rgba\(255,255,255,0\)_100%\)/);
  assert.match(sectionSource, /rounded-t-\[20px\]/);
  assert.match(sectionSource, /w-\[230px\]/);
  assert.match(sectionSource, /w-\[1200px\]/);
  assert.match(sectionSource, /-mx-6 w-\[calc\(100%\+48px\)\] overflow-x-auto px-6/);
  assert.match(sectionSource, /sm:-mx-10 sm:w-\[calc\(100%\+80px\)\] sm:px-10/);
  assert.match(sectionSource, /h-8 bg-\[#24292f\] text-white/);
  assert.match(sectionSource, /pl-5 text-left text-xs font-medium leading-\[17px\] tracking-\[0\.24px\]/);
  assert.match(sectionSource, /h-11 border-b border-\[#dae1e7\]/);

  assert.doesNotMatch(sectionSource, /rounded-\[28px\] border border-slate-200/);
  assert.doesNotMatch(sectionSource, /shadow-\[0_14px_40px/);
  assert.doesNotMatch(sectionSource, />\s*↗\s*</);
  assert.doesNotMatch(sectionSource, /bg-slate-50 text-slate-950/);
  assert.doesNotMatch(sectionSource, /lg:grid-cols-3/);

  assert.doesNotMatch(sectionSource, /export const Pricing = Object\.assign/);
  assert.doesNotMatch(sectionSource, /export const Plan = Object\.assign/);
  assert.doesNotMatch(sectionSource, /type CompareTableColumn =/);
  assert.doesNotMatch(sectionSource, /type CompareTableRowGroup =/);
});
