import test from "node:test";
import assert from "node:assert/strict";
import { readSource, sourceExists } from "../../../../helpers/source-readers.mjs";

test("/t/plans routes keep pricing copy in route pages while the section module only provides pricing UI primitives", () => {
  const routeSource = readSource("src/app/t/plans/page.tsx");
  const aipRouteSource = readSource("src/app/t/plans/aip/page.tsx");
  const acpRouteSource = readSource("src/app/t/plans/acp/page.tsx");
  const sectionSource = readSource("src/components/sections/plans/section.tsx");

  assert.equal(sourceExists("src/app/t/plans/plans-page-content.tsx"), false);
  assert.equal(sourceExists("src/app/t/plans/[product]/page.tsx"), false);

  assert.match(routeSource, /import PlansAIPPage from "\.\/aip\/page"/);
  assert.match(routeSource, /return <PlansAIPPage \/>/);
  assert.match(routeSource, /redirect\(redirectTarget\)/);
  assert.match(routeSource, /return `plans\/\$\{product\}/);

  assert.match(aipRouteSource, /canonical: "\/t\/plans\/aip"/);
  assert.doesNotMatch(aipRouteSource, /export function AipPlansContent\(\)/);
  assert.match(aipRouteSource, /<PricingRoot>/);
  assert.match(aipRouteSource, /<PricingHeader>/);
  assert.match(aipRouteSource, /<PricingContextProvider defaultActiveTab="aip">/);
  assert.match(aipRouteSource, /<ProductTabs>/);
  assert.match(aipRouteSource, /<ProductTab name="aip">/);
  assert.match(aipRouteSource, /<ProductTab name="acp">/);
  assert.match(aipRouteSource, /<PlanCard type="primary">/);
  assert.match(aipRouteSource, /<PlanCard type="black">/);
  assert.match(aipRouteSource, /<PlanFeature supported=\{true\}>月間800クレジット<\/PlanFeature>/);
  assert.match(aipRouteSource, /<CompareTable>/);
  assert.match(aipRouteSource, /<CompareTableHead>/);
  assert.match(aipRouteSource, /<CompareTableSection title="一般">/);
  assert.match(aipRouteSource, /<CompareTableRow label="料金">/);
  assert.match(aipRouteSource, /<CompareTableTextCell isBold>\$20\/月<\/CompareTableTextCell>/);
  assert.match(aipRouteSource, /<CompareTableBooleanCell supported=\{false\} \/>/);
  assert.match(aipRouteSource, /<CompareTableCheckLabelCell>最大30日間<\/CompareTableCheckLabelCell>/);

  assert.match(acpRouteSource, /canonical: "\/t\/plans\/acp"/);
  assert.match(acpRouteSource, /<PricingRoot>/);
  assert.match(acpRouteSource, /<PricingHeader>/);
  assert.match(acpRouteSource, /<PricingContextProvider defaultActiveTab="acp">/);
  assert.match(acpRouteSource, /<ProductTabs>/);
  assert.match(acpRouteSource, /<ProductTab name="aip">/);
  assert.match(acpRouteSource, /<ProductTab name="acp">/);
  assert.match(acpRouteSource, /<PlanCard type="primary">/);
  assert.match(acpRouteSource, /<PlanCard type="black">/);
  assert.match(acpRouteSource, /<PlanTitle>コミュニティ<\/PlanTitle>/);
  assert.match(acpRouteSource, /href="\/contact-us\?inquiry=quote-request&product=acp"/);

  for (const source of [routeSource, aipRouteSource, acpRouteSource, sectionSource]) {
    assert.doesNotMatch(source, /PlansContentShell/);
    assert.doesNotMatch(source, /PlansPageContent/);
    assert.doesNotMatch(source, /AipPlansContent/);
  }

  assert.doesNotMatch(aipRouteSource, /href="\/t\/plans\//);
  assert.doesNotMatch(acpRouteSource, /href="\/t\/plans\//);
  assert.doesNotMatch(aipRouteSource, /PlansPreviewPage/);
  assert.doesNotMatch(aipRouteSource, /const Pricing = Object\.assign/);
  assert.doesNotMatch(aipRouteSource, /const Plan = Object\.assign/);
  assert.doesNotMatch(aipRouteSource, /rows=\{\[/);
  assert.doesNotMatch(aipRouteSource, /columns=\{\[/);
  assert.doesNotMatch(aipRouteSource, /const aipPlans\s*:/);
  assert.doesNotMatch(acpRouteSource, /const acpPlans\s*:/);
  assert.doesNotMatch(aipRouteSource, /const aipComparisonGroups\s*:/);
  assert.doesNotMatch(aipRouteSource, /products=\{\[/);
  assert.doesNotMatch(aipRouteSource, /PlansProductSwitcher/);

  assert.match(sectionSource, /export function PricingRoot\(/);
  assert.match(sectionSource, /export function PricingHeader\(/);
  assert.match(sectionSource, /export function PricingContextProvider/);
  assert.match(sectionSource, /searchParams\.has\("acp"\)/);
  assert.match(sectionSource, /usePathname\(\)/);
  assert.match(sectionSource, /function getPlansProductHref\(pathname: string, product: string\)/);
  assert.match(sectionSource, /lastSegment === "aip" \|\| lastSegment === "acp"/);
  assert.match(sectionSource, /href: getPlansProductHref\(pathname, name\)/);
  assert.doesNotMatch(sectionSource, /href=\{`\/t\/plans/);
  assert.match(sectionSource, /export function PlanRoot\(/);
  assert.match(sectionSource, /export function PlanCard\(/);
  assert.match(sectionSource, /export function PlansHeroTitle[\s\S]*tracking-normal/);
  assert.doesNotMatch(sectionSource, /export function PlansHeroTitle[\s\S]*tracking-\[-0\.03em\]/);
  assert.match(sectionSource, /export function PlanCard[\s\S]*rounded-t-\[20px\]/);
  assert.doesNotMatch(sectionSource, /export function PlanCard[\s\S]*overflow-hidden/);
  assert.match(sectionSource, /rounded-\[6px\]/);
  assert.match(sectionSource, /leading-\[16px\]/);
  assert.match(sectionSource, /<span className="leading-\[22px\]">\{children\}<\/span>/);
  assert.match(sectionSource, /bg-\[#0762d4\]/);
  assert.match(sectionSource, /bg-\[#141920\]/);
  assert.match(sectionSource, /text-\[#f6f6f6\]/);
  assert.doesNotMatch(sectionSource, /rounded-md/);
  assert.doesNotMatch(sectionSource, /bg-\[#1d4ed8\]/);
  assert.doesNotMatch(sectionSource, /bg-slate-950/);
  assert.match(sectionSource, /function ButtonChevronIcon\(/);
  assert.match(sectionSource, /viewBox="0 0 7 12"/);
  assert.match(sectionSource, /M7 6L0\.865033 12L0 11\.154L5\.26381 6L0 0\.846L0\.865033 0L7 6Z/);
  assert.match(sectionSource, /export function CompareTable\(/);
  assert.match(sectionSource, /export function CompareTableHead\(/);
  assert.match(sectionSource, /export function CompareTableSection\(/);
  assert.match(sectionSource, /export function CompareTableRow\(/);
  assert.match(sectionSource, /export function CompareTableTextCell\(/);
  assert.match(sectionSource, /export function CompareTableBooleanCell\(/);
  assert.match(sectionSource, /export function CompareTableCheckLabelCell\(/);
  assert.match(sectionSource, /cloneElement\(child as ReactElement<ProductTabProps>, \{/);
  assert.match(sectionSource, /gap-3 border-b-2 border-\[#dae1e7\]/);
  assert.match(sectionSource, /min-\[481px\]:gap-5/);
  assert.match(sectionSource, /min-\[769px\]:gap-10/);
  assert.match(sectionSource, /min-\[1025px\]:gap-\[60px\]/);
  assert.match(sectionSource, /flex-1 cursor-pointer/);
  assert.match(sectionSource, /min-\[769px\]:pb-5/);
  assert.match(sectionSource, /min-\[481px\]:text-\[22px\]/);
  assert.match(sectionSource, /min-\[481px\]:leading-\[30px\]/);
  assert.match(sectionSource, /min-\[769px\]:text-\[26px\]/);
  assert.match(sectionSource, /min-\[769px\]:leading-\[34px\]/);
  assert.match(sectionSource, /min-\[481px\]:text-\[13px\]/);
  assert.match(sectionSource, /min-\[481px\]:leading-\[20px\]/);
  assert.match(sectionSource, /min-\[769px\]:text-sm/);
  assert.match(sectionSource, /min-\[769px\]:leading-\[22px\]/);
  assert.match(sectionSource, /gap-20/);
  assert.match(sectionSource, /bg-\[linear-gradient\(180deg,#edf0f7_0%,#edf0f7_26\.89%,rgba\(255,255,255,0\)_60%\)\]/);
  assert.match(sectionSource, /radial-gradient\(126\.36%_70\.17%_at_50%_86\.97%,#fff_0%,rgba\(255,255,255,0\)_100%\)/);
  assert.match(sectionSource, /rounded-t-\[20px\]/);
  assert.match(sectionSource, /w-\[230px\]/);
  assert.match(sectionSource, /h-\[2px\] w-full origin-top-left bg-\[#dae1e7\] \[transform:scaleY\(0\.5\)\]/);
  assert.match(sectionSource, /w-\[1200px\]/);
  assert.match(sectionSource, /-mx-6 w-\[calc\(100%\+48px\)\] overflow-x-auto px-6/);
  assert.match(sectionSource, /sm:-mx-10 sm:w-\[calc\(100%\+80px\)\] sm:px-10/);
  assert.match(sectionSource, /h-11 border-b border-\[#dae1e7\] bg-\[#2f3a49\] text-\[#f6f6f6\]/);
  assert.match(sectionSource, /pl-5 text-left text-xs font-medium leading-\[17px\] tracking-\[0\.24px\]/);
  assert.match(sectionSource, /h-11 border-b border-\[#dae1e7\]/);
  assert.match(sectionSource, /text-sm font-light leading-\[22px\] text-\[#24292f\]/);
  assert.match(sectionSource, /function CompareTableStatusIcon\(/);
  assert.match(sectionSource, /viewBox="0 0 32 32"/);
  assert.match(sectionSource, /fill=\{supported \? "#0762d4" : "#d43823"\}/);
  assert.match(sectionSource, /h-\[15px\] w-\[15px\]/);
  assert.match(sectionSource, /M16 30C23\.732 30 30 23\.732 30 16C30 8\.26801/);
  assert.match(sectionSource, /M2 16C2 8\.28 8\.28 2 16 2C23\.72 2 30 8\.28 30 16/);

  assert.doesNotMatch(sectionSource, /h-8 bg-\[#24292f\] text-white/);
  assert.doesNotMatch(sectionSource, /rounded-\[28px\] border border-slate-200/);
  assert.doesNotMatch(sectionSource, /shadow-\[0_14px_40px/);
  assert.doesNotMatch(sectionSource, />\s*↗\s*</);
  assert.doesNotMatch(sectionSource, /bg-slate-50 text-slate-950/);
  assert.doesNotMatch(sectionSource, /lg:grid-cols-3/);
  assert.doesNotMatch(sectionSource, /export const Pricing = Object\.assign/);
  assert.doesNotMatch(sectionSource, /export const Plan = Object\.assign/);
  assert.doesNotMatch(sectionSource, /type CompareTableColumn =/);
  assert.doesNotMatch(sectionSource, /type CompareTableRowGroup =/);
});
