import test from "node:test";
import assert from "node:assert/strict";
import { readSource, sourceExists } from "../../../../helpers/source-readers.mjs";

test("/platforms/acp reflects the current access-control scope while keeping copy in the route", () => {
  assert.equal(sourceExists("src/app/platforms/acp/page.tsx"), true);
  assert.equal(sourceExists("src/components/sections/acp/service-page.tsx"), true);
  assert.equal(sourceExists("src/components/sections/acp/feature-browser.tsx"), true);

  const routeSource = readSource("src/app/platforms/acp/page.tsx");
  const sectionSource = readSource("src/components/sections/acp/service-page.tsx");
  const browserSource = readSource("src/components/sections/acp/feature-browser.tsx");

  assert.match(routeSource, /canonical: "\/platforms\/acp"/);
  assert.match(routeSource, /robots:\s*\{\s*index: true,\s*follow: true,\s*\}/s);
  assert.match(routeSource, /<SiteHeader \/>/);
  assert.match(routeSource, /<SiteFooter \/>/);
  assert.match(routeSource, /QueryPie ACP｜Access Control Platform<\/p>/);
  assert.match(routeSource, /text-\[#0969DA\]">QueryPie ACP｜Access Control Platform/);
  assert.match(routeSource, /アクセス統制を、AI時代の共通基盤へ。/);
  assert.match(routeSource, /Web\/SaaS、MCPへのアクセスを一元制御するプラットフォームです。/);
  assert.match(routeSource, /最小権限、申請・承認、監査ログ、セッション記録、DLP/);
  assert.match(routeSource, /すべてのインフラとAIのアクセスを、ひとつの基盤で統制/);
  assert.doesNotMatch(routeSource, /<AcpIntegrationsTitle>[\s\S]*?<br \/>[\s\S]*?<\/AcpIntegrationsTitle>/);
  assert.match(routeSource, /50種類以上のシステムと連携/);
  assert.match(routeSource, /連携対象に加え、権限・ポリシー・監査を一つの基盤で統制する価値を明確化します。/);
  assert.match(routeSource, />ACPの統合機能を見る→<\//);

  assert.match(routeSource, /Database Access Control/);
  assert.match(routeSource, /System Access Control/);
  assert.match(routeSource, /Kubernetes Access Control/);
  assert.match(routeSource, /Web Access Control/);
  assert.match(routeSource, /MCP Access Control/);
  assert.match(routeSource, /DAC｜データベースアクセス制御/);
  assert.match(routeSource, /SAC｜システムアクセス制御/);
  assert.match(routeSource, /KAC｜Kubernetesアクセス制御/);
  assert.match(routeSource, /WAC｜Web\/SaaSアクセス制御/);
  assert.match(routeSource, /MAC｜MCPアクセス制御/);
  assert.match(routeSource, /QueryPie DACは、クラウドとオンプレミスのデータベースを横断して可視化・統制します。/);
  assert.match(routeSource, /QueryPie SACは、AWS、GCP、Azure、オンプレミスのサーバーアクセスを一元管理します。/);
  assert.match(routeSource, /QueryPie KACは、クラウドとオンプレミスのKubernetes環境をまとめて可視化・統制します。/);
  assert.match(routeSource, /QueryPie WACは、管理画面やSaaSへのアクセスを統制し、操作ログと画面記録を取得します。/);
  assert.match(routeSource, /QueryPie MACは、MCPツールやMCPサーバーの呼び出しを、ポリシーに基づき一元制御します。/);
  assert.match(routeSource, /AIエージェントによるツール利用を、安全に統制/);
  assert.match(routeSource, /acp-dac\.mp4/);
  assert.match(routeSource, /acp-mac\.mp4/);
  assert.match(routeSource, /ACP AI Pack/);
  assert.match(routeSource, /<AcpAiPackCard icon=\{MessageSquareText\}>/);
  assert.match(routeSource, /<AcpAiPackCard icon=\{Network\}>/);
  assert.match(routeSource, /<AcpAiPackCard icon=\{ClipboardCheck\}>/);
  assert.match(routeSource, /<AcpAiPackCardTitle>AI Chat<\/AcpAiPackCardTitle>/);
  assert.match(routeSource, /<AcpAiPackCardTitle>ACP MCP<\/AcpAiPackCardTitle>/);
  assert.match(routeSource, /<AcpAiPackCardTitle>AI Skills<\/AcpAiPackCardTitle>/);
  assert.match(routeSource, /href="\/contact-us\?inquiry=ai-consulting&product=acp"/);
  assert.doesNotMatch(routeSource, /learnMoreHref=/);
  assert.doesNotMatch(routeSource, /AipFreeTrialCtaSection/);
  assert.doesNotMatch(routeSource, /簡単インストール、簡単使用/);

  assert.match(sectionSource, /export function AcpHeroDiagram/);
  assert.match(sectionSource, /role-ai-agents\.png/);
  assert.match(sectionSource, /connections\.svg/);
  assert.match(sectionSource, /target-mcp\.svg/);
  assert.match(sectionSource, /function FlowPulse/);
  assert.match(sectionSource, /<animateMotion/);
  assert.match(sectionSource, /acp-hero-flow-glow/);
  assert.match(sectionSource, /shieldPulseTimings/);
  assert.match(sectionSource, /left: \{ keyTimes: "0;0\.05;0\.18;0\.26;1"/);
  assert.match(sectionSource, /center: \{ keyTimes: "0;0\.4;0\.5;0\.6;1"/);
  assert.match(sectionSource, /right: \{ keyTimes: "0;0\.74;0\.87;0\.96;1"/);
  assert.match(sectionSource, /acp-hero-controller-pulse/);
  assert.match(sectionSource, /shield-mask\.png/);
  assert.match(sectionSource, /DLP \(Data Loss Prevention\)/);
  assert.match(sectionSource, /iconTone/);
  assert.match(sectionSource, /brightness-0/);
  assert.match(sectionSource, /flex w-full justify-center/);
  assert.match(sectionSource, /w-fit max-w-full/);
  assert.match(sectionSource, /text-left text-\[13px\].*sm:text-\[15px\]/);
  assert.match(sectionSource, /AI活用を守り切れません。<\/span>/);
  assert.match(sectionSource, /QueryPie ACPは、統制の仕組みと対象環境を一つの基盤に集約します。<\/span>/);
  assert.match(sectionSource, /ユーザー/);
  assert.match(sectionSource, /bg-\[#EAF2FF\]/);
  assert.match(sectionSource, /Home-ACP\.mp4#t=0\.001/);
  assert.doesNotMatch(sectionSource, /youtube\.com\/embed\/AWnknC76Jpo/);
  assert.doesNotMatch(routeSource, /AcpGovernanceSection/);
  assert.doesNotMatch(sectionSource, /export function AcpGovernanceSection/);
  assert.match(sectionSource, /export function AcpAiPackSection/);
  assert.match(sectionSource, /export function AcpAiPackVideo/);
  assert.match(sectionSource, /AcpFeatureSection.*pb-\[100px\] pt-\[80px\]/s);
  assert.match(sectionSource, /max-w-\[760px\] self-center text-left text-\[16px\]/);
  assert.match(sectionSource, /AcpIntegrationsSection.*py-\[48px\].*lg:py-\[56px\]/s);
  assert.match(sectionSource, /lg:grid-cols-\[minmax\(0,1fr\)_430px\]/);
  assert.match(sectionSource, /lg:text-\[28px\] lg:leading-\[37px\] lg:whitespace-nowrap/);
  assert.match(sectionSource, /lg:max-w-\[calc\(100%-24px\)\]/);
  assert.match(sectionSource, /width=\{430\} height=\{450\}/);

  assert.match(browserSource, /mediaSrc: string/);
  assert.match(browserSource, /mediaAlt: string/);
  assert.match(browserSource, /<article key=\{category\.label\}/);
  assert.match(browserSource, /<video/);
  assert.match(browserSource, /mediaFirstOnDesktop/);
  assert.match(browserSource, /md:grid-cols-2 md:gap-\[60px\]/);
  assert.match(browserSource, /englishLabel: string/);
  assert.match(browserSource, /abbreviation: string/);
  assert.match(browserSource, /split\("｜", 2\)/);
  assert.match(browserSource, /text-\[26px\] font-semibold.*category\.abbreviation/s);
  assert.match(browserSource, /inline-flex rounded-full bg-\[#EAF2FF\].*category\.label/s);
  assert.match(browserSource, /text-\[13px\] font-light/);
  assert.match(browserSource, /text-\[26px\].*sm:text-\[30px\]/);
  assert.doesNotMatch(browserSource, /詳細を見る/);
  assert.doesNotMatch(browserSource, /next\/link/);
  assert.doesNotMatch(browserSource, /製品を選択/);
  assert.match(sectionSource, /lg:items-center lg:justify-center/);
  assert.match(sectionSource, /icon: LucideIcon/);
  assert.match(sectionSource, /min-h-\[136px\]/);
  assert.match(sectionSource, /min-w-0 translate-y-2/);
  assert.match(sectionSource, /lg:w-\[400px\] lg:max-w-\[36%\] lg:flex-none/);
  assert.match(sectionSource, /lg:w-\[600px\] lg:max-w-\[50%\]/);

  const heroPrimitiveSource = readSource("src/components/sections/acp/hero-primitives.tsx");
  assert.match(heroPrimitiveSource, /max-w-\[1080px\].*text-left.*text-\[16px\]/);
});
