import test from "node:test";
import assert from "node:assert/strict";
import { readSource, sourceExists } from "../../../../helpers/source-readers.mjs";

test("/platforms/acp reflects the current access-control scope while keeping copy in the route", () => {
  assert.equal(sourceExists("src/app/platforms/acp/page.tsx"), true);
  assert.equal(sourceExists("src/components/sections/acp/service-page.tsx"), true);
  assert.equal(sourceExists("src/components/sections/acp/feature-browser.tsx"), true);

  const routeSource = readSource("src/app/platforms/acp/page.tsx");
  const sectionSource = readSource("src/components/sections/acp/service-page.tsx");
  const browserSource = readSource("src/components/sections/acp/feature-browser.tsx");

  assert.match(routeSource, /canonical: "\/platforms\/acp"/);
  assert.match(routeSource, /robots:\s*\{\s*index: true,\s*follow: true,\s*\}/s);
  assert.match(routeSource, /<SiteHeader \/>/);
  assert.match(routeSource, /<SiteFooter \/>/);
  assert.match(routeSource, /アクセス統制を、AI時代の共通基盤へ。/);
  assert.match(routeSource, /Web\/SaaS、MCPへのアクセスを一元制御するプラットフォームです。/);
  assert.match(routeSource, /最小権限、申請・承認、監査ログ、セッション記録、DLP/);
  assert.match(routeSource, /インフラとAIのアクセスを一元管理/);
  assert.match(routeSource, /50種類以上のシステムと連携/);
  assert.match(routeSource, /アクセス権限・ポリシー・監査を一つの基盤で統制します。/);
  assert.match(routeSource, />ACPの統合機能を見る<\//);

  assert.match(routeSource, /Database Access Control/);
  assert.match(routeSource, /System Access Control/);
  assert.match(routeSource, /Kubernetes Access Control/);
  assert.match(routeSource, /Web Access Control/);
  assert.match(routeSource, /MCP Access Control/);
  assert.match(routeSource, /DAC｜データベースアクセス制御/);
  assert.match(routeSource, /SAC｜システムアクセス制御/);
  assert.match(routeSource, /KAC｜Kubernetesアクセス制御/);
  assert.match(routeSource, /WAC｜Web\/SaaSアクセス制御/);
  assert.match(routeSource, /MAC｜MCPアクセス制御/);
  assert.match(routeSource, /acp-dac\.mp4/);
  assert.match(routeSource, /acp-mac\.mp4/);
  assert.match(routeSource, /ACP AI Pack/);
  assert.match(routeSource, /<AcpAiPackCardTitle>AI Chat<\/AcpAiPackCardTitle>/);
  assert.match(routeSource, /<AcpAiPackCardTitle>ACP MCP<\/AcpAiPackCardTitle>/);
  assert.match(routeSource, /<AcpAiPackCardTitle>AI Skills<\/AcpAiPackCardTitle>/);
  assert.match(routeSource, /href="\/contact-us\?inquiry=ai-consulting&product=acp"/);
  assert.doesNotMatch(routeSource, /learnMoreHref=/);
  assert.doesNotMatch(routeSource, /AipFreeTrialCtaSection/);
  assert.doesNotMatch(routeSource, /簡単インストール、簡単使用/);

  assert.match(sectionSource, /export function AcpHeroDiagram/);
  assert.match(sectionSource, /role-ai-agents\.png/);
  assert.match(sectionSource, /connections\.svg/);
  assert.match(sectionSource, /target-mcp\.svg/);
  assert.match(sectionSource, /function FlowPulse/);
  assert.match(sectionSource, /<animateMotion/);
  assert.match(sectionSource, /shield-mask\.png/);
  assert.match(sectionSource, /DLP \(Data Loss Prevention\)/);
  assert.match(sectionSource, /iconTone/);
  assert.match(sectionSource, /brightness-0/);
  assert.match(sectionSource, /flex w-full justify-center/);
  assert.match(sectionSource, /w-fit max-w-full/);
  assert.match(sectionSource, /text-left text-\[13px\].*sm:text-\[15px\]/);
  assert.match(sectionSource, /AI活用を守り切れません。<\/span>/);
  assert.match(sectionSource, /QueryPie ACPは、統制の仕組みと対象環境を一つの基盤に集約します。<\/span>/);
  assert.match(sectionSource, /ユーザー/);
  assert.match(sectionSource, /bg-\[#EAF2FF\]/);
  assert.match(sectionSource, /Home-ACP\.mp4#t=0\.001/);
  assert.doesNotMatch(sectionSource, /youtube\.com\/embed\/AWnknC76Jpo/);
  assert.doesNotMatch(routeSource, /AcpGovernanceSection/);
  assert.doesNotMatch(sectionSource, /export function AcpGovernanceSection/);
  assert.match(sectionSource, /export function AcpAiPackSection/);
  assert.match(sectionSource, /export function AcpAiPackVideo/);
  assert.match(sectionSource, /max-w-\[760px\] self-center text-left text-\[16px\]/);
  assert.match(sectionSource, /AcpIntegrationsSection.*py-\[56px\].*lg:py-\[64px\]/s);
  assert.match(sectionSource, /lg:grid-cols-\[minmax\(0,1fr\)_430px\]/);
  assert.match(sectionSource, /width=\{430\} height=\{450\}/);

  assert.match(browserSource, /mediaSrc: string/);
  assert.match(browserSource, /mediaAlt: string/);
  assert.match(browserSource, /<article key=\{category\.label\}/);
  assert.match(browserSource, /<video/);
  assert.match(browserSource, /mediaFirstOnDesktop/);
  assert.match(browserSource, /md:grid-cols-2 md:gap-\[60px\]/);
  assert.match(browserSource, /englishLabel: string/);
  assert.match(browserSource, /text-\[13px\] font-light/);
  assert.match(browserSource, /text-\[28px\].*sm:text-\[34px\]/);
  assert.doesNotMatch(browserSource, /詳細を見る/);
  assert.doesNotMatch(browserSource, /next\/link/);
  assert.doesNotMatch(browserSource, /製品を選択/);
  assert.match(sectionSource, /lg:items-center/);
  assert.match(sectionSource, /lg:w-\[680px\] lg:max-w-\[57%\]/);

  const heroPrimitiveSource = readSource("src/components/sections/acp/hero-primitives.tsx");
  assert.match(heroPrimitiveSource, /max-w-\[1080px\].*text-left.*text-\[16px\]/);
});
